phone:
    pattern:  /
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:index" }

phone_show:
    pattern:  /{id}/show
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:show" }

phone_new:
    pattern:  /new
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:new" }

phone_create:
    pattern:  /create
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:create" }
    requirements: { _method: post }

phone_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:edit" }

phone_update:
    pattern:  /{id}/update
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:update" }
    requirements: { _method: post|put }

phone_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "S118EbrahimiBundle:PhoneEntity:delete" }
    requirements: { _method: post|delete }
