<?php

namespace S118\EbrahimiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEntityRepository extends EntityRepository
{
}
